### ISSUE TITLE
Is it possible to install separatelly Poser and Painter nodes?

### ISSUE THREAD

**Issue by rezponze** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#54]
Hi!

I love your Painter and Poser nodes. Is there a chance I can install them without having to install all the other ones? 

Thanks!

**Comment by AlekPet** [comment]
> Hi!
> 
> I love your Painter and Poser nodes. Is there a chance I can install them without having to install all the other ones? 
> 
> Thanks! 

Hello, before piping, there was such an opportunity when, at startup, it automatically searched for nodes (folders with .py files ending in Node) and installed them, now I updated it because  the extension manager didn’t like it (https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/47#issue-2254613378), but the functionality remained, so I commented it out.  You can do the following, delete the folders of nodes that you do not need and install the old __init__.py file (https://raw.githubusercontent.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/b0ed9b7f1057a29f7f1ee6cb63ccb881b0ff28de/__init__.py).  Maybe I'll find a way to do this in a new one.

**Comment by rezponze** [comment]
Thanks for the answer! 

How do I install the old _init_.py after deleting the node folders I don't need?

**Comment by AlekPet** [comment]
> Thanks for the answer! 
> 
> How do I install the old _init_.py after deleting the node folders I don't need?

Download from the link above and replace it in the Comfyui_Custom_AlekPet_Nodes folder

**Comment by rezponze** [comment]
Thanks a lot again, I'm closing this issue.
