### ISSUE TITLE
painter node- previous paintings not saving with workflow reload? local storage + save options checked, but doesn’t seem to work

### ISSUE THREAD

**Issue by annasophiachristianahahn** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#57]
I have the most recent version of your nodes however I can’t seem to get the painter node to save what I draw in a way that can be recovered

Do I need to do anything else to make them work properly? I am using default settings and have tried switching between the BG vs image modes in settings, nothing seems to make a difference

Is there something I can do to make sure the paintings are saved with the workflow?

**Comment by AlekPet** [comment]
> I have the most recent version of your nodes however I can’t seem to get the painter node to save what I draw in a way that can be recovered
> 
> Do I need to do anything else to make them work properly? I am using default settings and have tried switching between the BG vs image modes in settings, nothing seems to make a difference
> 
> Is there something I can do to make sure the paintings are saved with the workflow?

Hi. It may not be saved in localStorage for several reasons.  1. The browser quota for saving in localStorage for an element has been exceeded, this can easily be seen in the browser if you open the console ctrl+shift+i, this happens if the canvas size is very large or there are a lot of already saved keys in localStorage["ComfUI_Painter"] (for good reason it was necessary  make sure that each created painternode has its own dictionary to save in localStorage, but there will be many keys in the localStorage space).  2. If the Save canvas checkbox is unchecked in the node settings.

**Comment by AlekPet** [comment]
Added an option to the settings to save PainterNode settings in json, for canvases that weigh a lot.
