### ISSUE TITLE
could you please add a node achive convert hexadecimal color values to hue values？

### ISSUE THREAD

**Issue by hexiaoyu946** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#62]
Dear developer, I want to convert hexadecimal color values to hue values, please ask if you can add a node to achieve this function, thank you very much
![屏幕截图 2024-06-19 011941](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/72909117/1860daff-60b2-4148-86c7-9002280828b1)

**Comment by AlekPet** [comment]
Hello, look at this, WAS_Image_Filters, WAS_Image_Levels (https://github.com/WASasquatch/was-node-suite-comfyui) might be useful. Maybe there are already nodes that do what you need, but I can also take a look when I have time. Maybe there are already nodes that do what you need, you just need to look, otherwise I can also look when I have time.

**Comment by AlekPet** [comment]
> thank you very much

Here: https://github.com/melMass/comfy_mtb#colors

**Comment by AlekPet** [comment]
Added my own version HEX to HUE, category extras.
