### ISSUE TITLE
Regarding the incorrect output of the console

### ISSUE THREAD

**Issue by yaoyao1106** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#72]
Can you handle these errors? 
That's too much! 

![864b41a5442bd2ff7cbb9071646f1c5](https://github.com/user-attachments/assets/d7e13fec-db5c-4425-88ab-931616544723)

**Comment by AlekPet** [comment]
Hi. Yes, I know about these errors, they are not critical, this is a topic for the node IDE, they usually appear at the first launch, it's all about the ace.js library, which is launched after and there are no such errors, because confyui scans all js files. I can correct these errors by adding the import of ace.js at the beginning of each design theme file.

**Comment by yaoyao1106** [comment]
> Hi. Yes, I know about these errors, they are not critical, this is a topic for the node IDE, they usually appear at the first launch, it's all about the ace.js library, which is launched after and there are no such errors, because confyui scans all js files. I can correct these errors by adding the import of ace.js at the beginning of each design theme file. I'll fix it soon...

 would like to express my gratitude to the author for their hard work.

**Comment by AlekPet** [comment]
Fixed files js IDENode, update and check.

**Comment by yaoyao1106** [comment]
> Fixed files js IDENode, update and check.

![R](https://github.com/user-attachments/assets/5754f28c-2027-4910-aafe-cfe4db2b5546)
