### ISSUE TITLE
Prompt outputs failed validation

### ISSUE THREAD

**Issue by goodluck821** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#89]
![屏幕截图 2024-10-17 181501](https://github.com/user-attachments/assets/828d16e6-d1bd-4e8d-a22e-a07c58398bb4)
PoseNode:
- Value not in list: image: 'Pose_0.png' not in []

**Comment by AlekPet** [comment]
Hi. I changed the directory to input and apparently forgot to correct the code in python when I created the preview in the combo sheet. Correct the code in the line https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/blob/master/PoseNode%2Fjs%2Fpose_node.js#L495 instead of "input" to "temp" and save, then I will correct it when I get to my computer :)

**Comment by goodluck821** [comment]
Thanks.That's OK!

**Comment by AlekPet** [comment]
> Thanks.That's OK!

Fixed code, please update 😄
